# DO NOT COMMIT THIS FILE
# Keystore signing configuration
keystore_path=C:/Users/0/AppData/Roaming/Godot/keystores/release.keystore
keystore_alias=wordpuzzle
# Password stored in Godot export_presets.cfg
